name: gowiem/fusionauth-go-client
description: Example Go client for FusionAuth

parameters:
  FUSIONAUTH_API_KEY:
  FUSIONAUTH_APP_ID:
    description: Unique identifier of the OAuth application to be generated
    default: c439b3ac-14e7-4661-a3db-ec42cade2119
  FUSIONAUTH_APP_NAME:
    description: Name to give the application registered with FusionAuth
    default: Architect
  PUBLIC_PORT: 8080

dependencies:
  gowiem/fusionauth: latest

services:
  app:
    build:
      context: ./
    interfaces:
      main: ${ parameters.PUBLIC_PORT }
    environment:
      PUBLIC_PORT: ${ parameters.PUBLIC_PORT }
      BASE_URL: ${ interfaces.app.url }
      FA_HOST: ${ dependencies['gowiem/fusionauth'].interfaces.external.host }
      FA_PORT: ${ dependencies['gowiem/fusionauth'].interfaces.external.port }
      FA_API_KEY: ${ parameters.FUSIONAUTH_API_KEY }
      FA_APP_ID: ${ parameters.FUSIONAUTH_APP_ID }
      FA_APP_NAME: ${ parameters.FUSIONAUTH_APP_NAME }

interfaces:
  app:
    description: Exposes the app to upstream traffic
    url: ${ services.app.interfaces.main.url }
